### ISSUE TITLE
rb_index函数文档可能存在问题

### ISSUE THREAD

**Issue by javartisan** [ChenHuajun/pg_roaringbitmap#15]
rb_index 函数的输入应该是 integer[]与integer而不是 `roaringbitmap,integer`, 辛苦有时间确认下

**Comment by ChenHuajun** [comment]
rb_index 函数的输入是 roaringbitmap,integer。

BTW：roaringbitmap的文本输入形式和integer[]相同，所有可能你看Sample以为是integer[]。
