### ISSUE TITLE
undefined symbol:Float8GetDatum（gp6.8）

### ISSUE THREAD

**Issue by jianghuzai** [ChenHuajun/pg_roaringbitmap#18]
Did your set  `enable_float8_byval=no`  when build  pg_roaringbitmap ? 
By default (enable_float8_byval=yes) Float8GetDatum should be inlined

_Originally posted by @ChenHuajun in https://github.com/ChenHuajun/pg_roaringbitmap/issues/3#issuecomment-497796289_

什么情况下要设置`enable_float8_byval=no`?

另外，readme.md中有提到Build on PostgreSQL 9.x or Greenplum 6.0只需要修改一下sql文件，其他编译流程不变。
Greenplum6.8就是基于Postgresql9.4.24的
我在配置好postgresql94-devel的环境后编译的结果，
放在Postgesql9.4可以正常使用，但是放在gp6.8中就会报undefined symbol:Float8GetDatum

**Comment by ChenHuajun** [comment]
到gp6的开发环境编译这个插件看下，gp6和pg9.4毕竟源码不一样。

**Comment by jianghuzai** [comment]
> 到gp6的开发环境编译这个插件看下，gp6和pg9.4毕竟源码不一样。

根据gp官网的教程准备好gp6的环境，但是其中并没有包好postgresql94-devel这个包，所以编译是找不到pg_config的。
如果把postgresql94-devel这个包装上，那是不是编译这个插件跟gp6并没有什么关系了呢？
ps: java狗一枚，对c和c++不熟悉

**Comment by ChenHuajun** [comment]
需要gp6的开发环境。比如使用源码安装gp6
