### ISSUE TITLE
Use in production ?

### ISSUE THREAD

**Issue by nhaberl** [ChenHuajun/pg_roaringbitmap#2]
Hey, would like to use it in production mode ... any experiences here so far ?

**Comment by lemire** [comment]
The underlying library, CRoaring, is definitively used in production.

**Comment by nhaberl** [comment]
Thanks, have been using it in C# so far and the performance is impressive (especially related to space used) and so far I wonder that it's quite "unpopular" on Postgres ...

**Comment by ChenHuajun** [comment]
pg_roaringbitmap has a relatively comprehensive RT test set, which runs before each release, and also checks for memory leaks, so I think it is ready be used in production. And we have many systems ourselves that had used it in a production environment.
