### ISSUE TITLE
.....

### ISSUE THREAD

**Issue by jiaobailong** [ChenHuajun/pg_roaringbitmap#20]
resolved~!

**Comment by jiaobailong** [comment]
[0m/a-one/bin/pg_roaringbitmap-0.5.3
[91m+ export 'CPLUS_INCLUDE_PATH=/usr/lib/gcc/x86_64-alpine-linux-musl/9.3.0/include'[0m[91m
[0m[91m+ export 'C_INCLUDE_PATH=/usr/lib/clang/9.0.0/include'
[0m[91m+ make
[0mgcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wcast-function-type -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -Wno-stringop-truncation -O2 -fPIC -std=c99 -Wno-error=maybe-uninitialized -Wno-declaration-after-statement -I. -I./ -I/usr/local/include/postgresql/server -I/usr/local/include/postgresql/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o roaringbitmap.o roaringbitmap.c
[91mIn file included from /usr/local/include/postgresql/server/c.h:62,
                 from /usr/local/include/postgresql/server/postgres.h:46,
                 from roaringbitmap.h:6,
                 from roaringbitmap.c:1:
/usr/lib/clang/9.0.0/include/stddef.h:18:19: error: missing binary operator before token "("
   18 | #if !__has_feature(modules)
      |                   ^
/usr/lib/clang/9.0.0/include/stddef.h:30:42: error: missing binary operator before token "("
   30 | #if !defined(_PTRDIFF_T) || __has_feature(modules)
      |                                          ^
/usr/lib/clang/9.0.0/include/stddef.h:41:39: error: missing binary operator before token "("
   41 | #if !defined(_SIZE_T) || __has_feature(modules)
      |                                       ^
[0m[91m/usr/lib/clang/9.0.0/include/stddef.h:55:42: error: missing binary operator before token "("

**Comment by xiaolin8** [comment]
> resolved~!

您好，请问能提供下你的镜像吗？我编译安装时总是失败 #21
