### ISSUE TITLE
编译warning

### ISSUE THREAD

**Issue by GPF199541** [ChenHuajun/pg_roaringbitmap#25]
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -std=c99 -Wno-error=maybe-uninitialized -Wno-declaration-after-statement -I. -I./ -I/opt/pgsql/include/server -I/opt/pgsql/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2   -c -o roaringbitmap.o roaringbitmap.c
In file included from roaringbitmap.h:99:0,
                 from roaringbitmap.c:1:
roaring.c:3785:5: warning: no previous prototype for ‘bitset_container_union_nocard’ [-Wmissing-prototypes]
 int bitset_container_##opname##_nocard(const bitset_container_t *src_1,   \
     ^
roaring.c:3815:1: note: in expansion of macro ‘BITSET_CONTAINER_FN’
 BITSET_CONTAINER_FN(union, |, _mm256_or_si256, vorrq_u64)
 ^~~~~~~~~~~~~~~~~~~
roaring.c:3785:5: warning: no previous prototype for ‘bitset_container_intersection_nocard’ [-Wmissing-prototypes]
 int bitset_container_##opname##_nocard(const bitset_container_t *src_1,   \
     ^
roaring.c:3819:1: note: in expansion of macro ‘BITSET_CONTAINER_FN’
 BITSET_CONTAINER_FN(intersection, &, _mm256_and_si256, vandq_u64)
 ^~~~~~~~~~~~~~~~~~~
In file included from roaringbitmap.h:99:0,
                 from roaringbitmap.c:1:
roaring.c:10821:7: warning: no previous prototype for ‘ra_get_container’ [-Wmissing-prototypes]
 void *ra_get_container(roaring_array_t *ra, uint16_t x, uint8_t *typecode) {
       ^~~~~~~~~~~~~~~~
roaring.c:10831:7: warning: no previous prototype for ‘ra_get_writable_container’ [-Wmissing-prototypes]
 void *ra_get_writable_container(roaring_array_t *ra, uint16_t x,
       ^~~~~~~~~~~~~~~~~~~~~~~~~
roaring.c:10839:7: warning: no previous prototype for ‘ra_get_writable_container_at_index’ [-Wmissing-prototypes]
 void *ra_get_writable_container_at_index(roaring_array_t *ra, uint16_t i,
       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
roaring.c:10944:8: warning: no previous prototype for ‘ra_size_in_bytes’ [-Wmissing-prototypes]
 size_t ra_size_in_bytes(roaring_array_t *ra) {
        ^~~~~~~~~~~~~~~~
gcc -Wall -Wmissing-prototypes -Wpointer-arith -Wdeclaration-after-statement -Werror=vla -Wendif-labels -Wmissing-format-attribute -Wimplicit-fallthrough=3 -Wformat-security -fno-strict-aliasing -fwrapv -fexcess-precision=standard -Wno-format-truncation -O2 -fPIC -shared -o roaringbitmap.so roaringbitmap.o -L/opt/pgsql/lib   -L/usr/lib64/llvm5.0/lib  -Wl,--as-needed -Wl,-rpath,'/opt/pgsql/lib',--enable-new-dtags  
/opt/rh/llvm-toolset-7/root/usr/bin/clang -Wno-ignored-attributes -fno-strict-aliasing -fwrapv -Wno-unused-command-line-argument -O2  -I. -I./ -I/opt/pgsql/include/server -I/opt/pgsql/include/internal  -D_GNU_SOURCE -I/usr/include/libxml2  -flto=thin -emit-llvm -c -o roaringbitmap.bc roaringbitmap.c

版本15.2,gcc 7.3.1 这个报warning有影响么

**Comment by ChenHuajun** [comment]
不影响，可以屏蔽告警
