### ISSUE TITLE
undefined symbol: Float8GetDatum

### ISSUE THREAD

**Issue by Jasonjunzhou** [ChenHuajun/pg_roaringbitmap#3]
I'm trying to install the extension on postgresql 11.2 I'm getting the error :could not load library "/usr/pgsql-11/lib/roaringbitmap.so": /usr/pgsql-11/lib/roaringbitmap.so: undefined symbol: Float8GetDatum

I got the error when I execute 'psql -c "create extension roaringbitmap"'

Then I upgraded postgresql 11.2 to 11.3 And rebulid the extension，there is still report this error

Any idea what can I check ?

**Comment by ChenHuajun** [comment]
Did your set  `enable_float8_byval=no`  when build  pg_roaringbitmap ? 
By default (enable_float8_byval=yes) Float8GetDatum should be inlined

**Comment by brandonstack** [comment]
I got this error while creating extensions on postgresql 10 and 11.
Sorry about my poor make knowledge, where can I change this arguments? thanks.

**Comment by Jasonjunzhou** [comment]
I solved my problem in the following way.

1. Try checking the postgresql version to confirm that only one version is installed.
    If not, delete the previous version
2. Check if the environment variable is configured completely
3. Rbulid the extension

4. If you use yum to install postgresql, you might get an error about clang when you buliding the extension. Try to install clang and llvm
5. There may be problems with gcc and cmake versions when you install clang and llvm. Try to manually compile and install them
6. Rebuild the extension     "make CLANG=your/path/clang"

Hope it helps you.

**Comment by brandonstack** [comment]
Thanks for your time, It really helps.

**Comment by ren2014** [comment]
Thanke for your help.
I solved this problem after i delete previous version
