### ISSUE TITLE
如何在多个schema上使用该插件？

### ISSUE THREAD

**Issue by JKeyZ** [ChenHuajun/pg_roaringbitmap#4]
我们线上环境存在多个schema使用该插件的情况。但该插件在创建时，只能在执行创建命令的schema上使用。其他schema上使用时，报异常：type "roaringbitmap" does not exist
我已把该插件加入到shared_preload_libraries配置项中，但不起作用。
请教该如何使用，才能使多个schema使用该插件？

**Comment by ChenHuajun** [comment]
看下pg_roaringbitmap安装在哪个schema （psql的\dx可以看）。 默认是public，public下默认都是可见的。如果不是public，类型和所有的函数都要加上"schema."前缀

**Comment by JKeyZ** [comment]
好的，谢谢


发自我的 iPhone
